services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    env_file:
      - .env

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery --app core worker --loglevel INFO"
    depends_on:
      - web
      - redis
      - db
    restart: on-failure
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      sh -c "python manage.py wait_for_db &&
             celery --app core beat --loglevel info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - web
      - db
      - redis
    restart: on-failure
    env_file:
      - .env

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: "celery --app core flower --address=0.0.0.0"
    depends_on:
      - celery
    env_file:
      - .env
